# Generated by Django 4.2.7 on 2023-11-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=100, verbose_name='Clasificacion')),
                ('tipo_clasificacion', models.CharField(max_length=100, verbose_name='Tipo de Clasificacion')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'clasificacion',
                'verbose_name_plural': 'clasificacion',
                'db_table': 'clasificacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desarrollador', models.CharField(max_length=100, verbose_name='Desarrollador')),
                ('fundacion', models.DateField(verbose_name='Fundacion')),
                ('pais_origen', models.CharField(max_length=100, verbose_name='Pais Origen')),
                ('sitio_web', models.CharField(max_length=100, verbose_name='Sitio Web')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'desarrollador',
                'verbose_name_plural': 'desarrolladores',
                'db_table': 'desarrollador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('fundacion', models.DateField(verbose_name='Fundacion')),
                ('sitio_web', models.CharField(max_length=100, verbose_name='Sitio Web')),
                ('pais_origen', models.CharField(max_length=100, verbose_name='Pais Origen')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fehca_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de venta')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_videojuego', models.CharField(max_length=100, verbose_name='Titulo videojuego')),
                ('lanzamiento', models.DateField(verbose_name='Lanzamiento')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.desarrollador')),
            ],
            options={
                'verbose_name': 'videojuego',
                'verbose_name_plural': 'videojuegos',
                'db_table': 'videojuegos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100, verbose_name='Nombre de la tienda')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.ventas')),
                ('videojuego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.videojuegos')),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'tiendas',
                'db_table': 'tiendas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plataforma', models.CharField(max_length=100, verbose_name='Plataforma')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
                ('usuarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.usuarios')),
                ('videojuego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.videojuegos')),
            ],
            options={
                'verbose_name': 'plataforma',
                'verbose_name_plural': 'plataformas',
                'db_table': 'plataformas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=100, verbose_name='Nombre del genero')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.clasificacion')),
                ('videojuego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.videojuegos')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'db_table': 'genero',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_contrato', models.CharField(max_length=100, verbose_name='Descripcion del contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio de contrato')),
                ('fecha_limite', models.DateField(verbose_name='Fecha limite de contrato')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.desarrollador')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vistas.empresa')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
    ]
